---
nexus_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64343635383030333335353561323036666464623265326431326237626236396439343165383939
          6461643139343464326230306238306266376166326237630a336564386666313562663135326135
          36396663356139333865366265313864336238663238313133623138633666613462333832663363
          3134326264623635350a373362643561656633313033326538353165666533346130613232343262
          3230
